### ISSUE TITLE
第二次加入世界时卡死bug

### ISSUE THREAD

**Issue by BrokenDawn627** [the-doo/x-enchant#3]
当你进入一个世界之后，退出并返回主菜单，然后再次加入世界或是新建世界时会导致卡死，似乎是光环附魔的问题，以下是崩溃信息。

> [20:26:00] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Attempted to register ID ResourceKey[minecraft:enchantment / x_enchant:halo_effect_-_effect.minecraft.speed] at different raw IDs (173, 273)! If you're trying to override an item, use .set(), not .register()!
	at net.minecraft.class_2370.handler$cfc000$setPre(class_2370.java:1150) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_31051(class_2370.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10273(class_2370.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_2370.method_10272(class_2370.java:97) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_39197(class_2378.java:424) ~[client-intermediary.jar:?]
	at net.minecraft.class_2378.method_10230(class_2378.java:420) ~[client-intermediary.jar:?]
	at com.doo.xenchant.enchantment.BaseEnchantment.<init>(BaseEnchantment.java:37) ~[x-enchant-1.18-2.jar:?]
	at com.doo.xenchant.enchantment.halo.HaloEnchantment.<init>(HaloEnchantment.java:23) ~[x-enchant-1.18-2.jar:?]
	at com.doo.xenchant.enchantment.halo.LivingHalo.<init>(LivingHalo.java:17) ~[x-enchant-1.18-2.jar:?]
	at com.doo.xenchant.enchantment.halo.EffectHalo.<init>(EffectHalo.java:23) ~[x-enchant-1.18-2.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.Iterator.forEachRemaining(Iterator.java:133) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at com.doo.xenchant.util.EnchantUtil.lambda$registerAll$5(EnchantUtil.java:98) ~[x-enchant-1.18-2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37) ~[fabric-lifecycle-events-v1-1.4.1+e66b59e93a-8c656a42126e6fdd.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cdb000$beforeSetupServer(MinecraftServer.java:3768) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:657) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[20:26:00] [Server thread/ERROR]: This crash report has been saved to: F:\Infinity-1.18\.minecraft\crash-reports\crash-2022-01-30_20.26.00-server.txt
[20:26:00] [Server thread/INFO]: Stopping server
[20:26:00] [Server thread/INFO]: Saving players
[20:26:00] [Server thread/INFO]: Saving worlds
[20:26:00] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_3218.method_8621()" because "$$5" is null
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:566) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:613) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3782(class_1132.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:723) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by the-doo** [comment]
大哥不好意思, 春节回家过年去了, 今天晚上更新修复😂😂😂

**Comment by BrokenDawn627** [comment]
谢啦 最近在做一个整合包 觉得你的模组特别好 另外药水光环能出个白名单就好了 毕竟有些负面效果

**Comment by the-doo** [comment]
bug 已经修复了 白名单问题 还需要 考虑怎么展示 所以可能晚一点
